version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - kay1_network
    volumes:
      - /home/sthax17/nginx.conf:/etc/nginx/nginx.conf
      - kay1_static:/data/static/
      - kay1_media:/data/media/

  django:
    image: kay1_django:3
    networks:
      - kay1_network
    volumes:
      - kay1_static:/home/kay1/staticfiles/
      - kay1_media:/home/kay1/media/



networks:
  kay1_network:

volumes:
  kay1_static:
  kay1_media: