version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - kay1_network
    volumes:
      - /home/sthax17/nginx.conf:/etc/nginx/nginx.conf
      - kay1_static:/data/static/
      - kay1_media:/data/media/

  django:
    image: kay1_django:4
    networks:
      - kay1_network
    volumes:
      - kay1_static:/home/kay1/staticfiles/
      - kay1_media:/home/kay1/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD


  mariadb:
    image: mariadb:10.5
    networks:
      - kay1_network
    volumes:
      - kay1_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD


networks:
  kay1_network:

volumes:
  kay1_static:
  kay1_media:
  kay1_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true